server:
  port: 8081

spring:
  application:
    name: ms-profile

  datasource:
    url: jdbc:postgresql://localhost:5432/profile_db
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health, info



